Parameters: 
  S3Bucket: 
    Description: Bucket name for lost and found site bucket
    Type: String
    Default: tyler-cad-project-images

Resources:
  # Product Lambda Functions
  getItems:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function to get all items from DynamoDB
      FunctionName: getItems
      Role: arn:aws:iam::638821506583:role/LabRole
      Code: 
        S3Bucket: !Ref S3Bucket
        S3Key: functions/getItems.zip
      Handler: getItems.lambda_handler
      Runtime: python3.11
      Timeout: 10
      
  addItems:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function to add items to DynamoDB
      FunctionName: addItems
      Role: arn:aws:iam::638821506583:role/LabRole
      Code: 
        S3Bucket: !Ref S3Bucket
        S3Key: functions/addItems.zip
      Handler: addItems.lambda_handler
      Runtime: python3.11
      Timeout: 10
     
  claimItems:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function to delete items in DynamoDB
      FunctionName: claimItems
      Role: arn:aws:iam::638821506583:role/LabRole
      Code: 
        S3Bucket: !Ref S3Bucket
        S3Key: functions/claimItems.zip
      Handler: claimItems.lambda_handler
      Runtime: python3.11
      Timeout: 10

  # API Gateway 
  ApiGateway: 
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: "CAD-Backend-API"
      Description: "Backend for Lost and Found Site"

  # Resource Paths
  # /lostItems
  ItemsResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: "lostItems"
      RestApiId: !Ref ApiGateway
  
  # /lostItems/{id}
  GetByIDResource: 
    Type: "AWS::ApiGateway::Resource"
    Properties:
      ParentId: !Ref ItemsResource
      PathPart: "{id}"
      RestApiId: !Ref ApiGateway

  # Methods
  # GET /product 
  GetItemsMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ItemsResource
      HttpMethod: "GET"
      AuthorizationType: "NONE"
      Integration:
        IntegrationHttpMethod: "GET"
        Type: "AWS"
        Uri: !Sub
          arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${getItems.Arn}/invocations
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true

  # POST /product
  PostItemsMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ItemsResource
      HttpMethod: "POST"
      AuthorizationType: "NONE"
      Integration:
        IntegrationHttpMethod: "POST"
        Type: "AWS"
        Uri: !Sub
          arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${addItems.Arn}/invocations
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true

  # DELETE /product
  DeleteItemMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref GetByIDResource
      HttpMethod: "DELETE"
      AuthorizationType: "NONE"
      Integration:
        IntegrationHttpMethod: "DELETE"
        Type: "AWS_PROXY"
        Uri: !Sub
          arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${claimItems.Arn}/invocations
      RequestParameters:
        method.request.path.id: true
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true

  # Lambda Permissions
  # Product Lambda Permissions
  getItemsPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !Ref getItems
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub
        arn:aws:execute-api:us-east-1:638821506583:${ApiGateway}/*/GET/lostItems
          
  postItemsPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !Ref addItems
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub
        arn:aws:execute-api:us-east-1:638821506583:${ApiGateway}/*/POST/lostItems
      
  deleteItemPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !Ref claimItems
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub
        arn:aws:execute-api:us-east-1:638821506583:${ApiGateway}/*/DELETE/lostItems/{id}
          
  # Enable CORS for /lostItems
  ItemCORSMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ItemsResource
      HttpMethod: "OPTIONS"
      AuthorizationType: "NONE"
      Integration:
        Type: "MOCK"
        RequestTemplates:
          application/json: "{ \"statusCode\": 200 }"
        IntegrationResponses:
          - StatusCode: "200"
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET,POST'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true
  
  # Enable CORS for /lostItems/{id}
  ItemIdCORSMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref GetByIDResource
      HttpMethod: "OPTIONS"
      AuthorizationType: "NONE"
      Integration:
        Type: "MOCK"
        RequestTemplates:
          application/json: "{ \"statusCode\": 200 }"
        IntegrationResponses:
          - StatusCode: "200"
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,DELETE'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - StatusCode: "200"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true
      
  # API Deployment 
  ApiDeployment:
    Type: "AWS::ApiGateway::Deployment"
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: "dev"
    DependsOn: 
      - GetItemsMethod
      - PostItemsMethod
      - DeleteItemMethod
      - ItemIdCORSMethod
      - ItemCORSMethod
  
Outputs:
  apiURL:
    Description: URL for API Gateway 
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/dev"


  

